Repository Nook-Book/Server, pull requests merged in 2024-12, with the labels that each got.

#38 [FEAT] Kaokao SDK 방식 로그인 기능 구현
  src/main/java/com/nookbook/domain/auth/application/AuthService.java
  src/main/java/com/nookbook/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/nookbook/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/nookbook/domain/auth/dto/request/SignInReq.java
  src/main/java/com/nookbook/domain/auth/dto/response/AuthRes.java
  src/main/java/com/nookbook/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/nookbook/domain/auth/presentation/AuthController.java
  src/main/java/com/nookbook/global/config/AppConfig.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
  src/main/java/com/nookbook/global/config/security/auth/company/Kakao.java
  src/main/java/com/nookbook/global/config/security/util/JwtTokenUtil.java
  src/main/java/com/nookbook/global/payload/ErrorCode.java
  src/main/java/com/nookbook/global/payload/ErrorResponse.java
Labels: feature 🪽

#39 Merge develop to main
  src/main/java/com/nookbook/domain/auth/application/AuthService.java
  src/main/java/com/nookbook/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/nookbook/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/nookbook/domain/auth/dto/request/SignInReq.java
  src/main/java/com/nookbook/domain/auth/dto/response/AuthRes.java
  src/main/java/com/nookbook/domain/auth/dto/response/LoginResponse.java
  src/main/java/com/nookbook/domain/auth/presentation/AuthController.java
  src/main/java/com/nookbook/global/config/AppConfig.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
  src/main/java/com/nookbook/global/config/security/auth/company/Kakao.java
  src/main/java/com/nookbook/global/config/security/util/JwtTokenUtil.java
  src/main/java/com/nookbook/global/payload/ErrorCode.java
  src/main/java/com/nookbook/global/payload/ErrorResponse.java
Labels: feature 🪽

#41 [FIX] ErrorResponse 생성 관련 오류 해결
  src/main/java/com/nookbook/domain/auth/application/IdTokenVerifier.java
  src/main/java/com/nookbook/global/config/security/util/JwtTokenUtil.java
  src/main/java/com/nookbook/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nookbook/global/payload/ErrorCode.java
  src/main/java/com/nookbook/global/payload/ErrorResponse.java
Labels: fix ⚒️

#43 [DEPLOY]
  src/main/resources/application.yml
Labels: fix ⚒️, cicd

#44 [DEPLOY]
  src/main/resources/application.yml
Labels: fix ⚒️, cicd
