Repository Nook-Book/Server, pull requests merged in 2024-10, with the labels that each got.

#23 [FEAT] 챌린지 관련 기능 구현 및 중간 PR
  src/main/java/com/nookbook/domain/auth/application/AuthService.java
  src/main/java/com/nookbook/domain/book/BookNotFoundException.java
  src/main/java/com/nookbook/domain/book/domain/repository/BookRepository.java
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/application/InvitationService.java
  src/main/java/com/nookbook/domain/challenge/application/ParticipantService.java
  src/main/java/com/nookbook/domain/challenge/domain/Challenge.java
  src/main/java/com/nookbook/domain/challenge/domain/ChallengeStatus.java
  src/main/java/com/nookbook/domain/challenge/domain/Invitation.java
  src/main/java/com/nookbook/domain/challenge/domain/Participant.java
  src/main/java/com/nookbook/domain/challenge/domain/ParticipantStatus.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/InvitationRepository.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/ParticipantRepository.java
  src/main/java/com/nookbook/domain/challenge/dto/request/ChallengeCreateReq.java
  src/main/java/com/nookbook/domain/challenge/dto/request/ChallengeUpdateReq.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeDetailRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeListDetailRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeListRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ParticipantStatusListRes.java
  src/main/java/com/nookbook/domain/challenge/exception/ChallengeNotAuthorizedException.java
  src/main/java/com/nookbook/domain/challenge/exception/ChallengeNotFoundException.java
  src/main/java/com/nookbook/domain/challenge/exception/ParticipantNotFoundException.java
  src/main/java/com/nookbook/domain/challenge/exception/ParticipantNotInChallengeException.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/collection/dto/response/MainCollectionListRes.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/domain/user/exception/UserDuplicateException.java
  src/main/java/com/nookbook/domain/user/exception/UserNotFoundException.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
  src/main/java/com/nookbook/global/DefaultAssert.java
  src/main/java/com/nookbook/global/exception/AuthorizedException.java
  src/main/java/com/nookbook/global/exception/DefaultAuthenticationException.java
  src/main/java/com/nookbook/global/exception/DefaultException.java
  src/main/java/com/nookbook/global/exception/DuplicateException.java
  src/main/java/com/nookbook/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nookbook/global/exception/NotFoundException.java
  src/main/java/com/nookbook/global/payload/ErrorCode.java
Labels: feature 🪽, fix ⚒️

#26 [FEAT]: 독서 리포트 조회 기능 구현
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/book/dto/response/BookStatisticsRes.java
  src/main/java/com/nookbook/domain/book/dto/response/MostReadCategoriesRes.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/collection/domain/repository/CollectionBookRepository.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/dto/response/MyInfoRes.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
  src/main/java/com/nookbook/domain/user/presentation/UserController.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
Labels: feature 🪽

#27 [FEAT]: 텍스트 추출 기능 구현
  .gitignore
  appspec.yml
  build.gradle
  scripts/setup_env.sh
  scripts/start.sh
  scripts/stop.sh
  src/main/java/com/nookbook/NookBookApplication.java
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/global/config/WebMvcConfig.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
  src/main/java/com/nookbook/infrastructure/s3/S3Uploader.java
  src/main/java/com/nookbook/infrastructure/vision/GoogleCloudVisionService.java
  src/main/java/com/nookbook/infrastructure/vision/GoogleStorageUploader.java
Labels: feature 🪽

#29 [FIX]: Json 파일 경로 수정
  scripts/setup_env.sh
Labels: cicd

#31 [DEPLOY]
  .github/workflows/deploy.yml
Labels: cicd

#33 [DEPLOY]
  scripts/setup_env.sh
  src/main/java/com/nookbook/NookBookApplication.java
Labels: cicd
