Repository Nook-Book/Server, pull requests merged in 2025-01, with the labels that each got.

#46 [FIX] 일시적 사용자 검증 해제
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/keyword/application/KeywordService.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: fix ⚒️

#47 [FEAT] 일시적 사용자 검증 단계 해제
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/keyword/application/KeywordService.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: fix ⚒️

#50 [FIX] 컬렉션 생성 시 JPQL 관련 반환 타입 오류 해결
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/domain/repository/CollectionRepository.java
Labels: fix ⚒️

#52 [FIX] 컬렉션 순서 변경 시 컬렉션 ID 파라미터 삭제
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
Labels: fix ⚒️

#53 [FIX] 컬렉션 순서 변경 시 컬렉션 ID 파라미터 삭제
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
Labels: fix ⚒️

#59 [FIX] 도서 상세 조회 오류 수정
  .github/ISSUE_TEMPLATE/issue_template.md
  src/main/java/com/nookbook/NookBookApplication.java
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/book/dto/response/BookRes.java
  src/main/java/com/nookbook/domain/collection/domain/repository/CollectionBookRepository.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
  src/main/java/com/nookbook/infrastructure/vision/GoogleCloudVisionService.java
  src/main/java/com/nookbook/infrastructure/vision/GoogleStorageUploader.java
Labels: feature 🪽, fix ⚒️

#61 [FIX] 현재 컬렉션 목록 조회 시 응답값에 isbn 정보 추가
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/response/CollectionBooksListDetailRes.java
Labels: fix ⚒️

#62 [FIX] 현재 컬렉션 목록 조회 시 응답값에 isbn 정보 추가
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/response/CollectionBooksListDetailRes.java
Labels: fix ⚒️

#64 [FIX] 모든 컬렉션 목록 조회 시 도서 수 응답에 포함
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/response/CollectionListDetailRes.java
Labels: fix ⚒️

#65 [FIX] 모든 컬렉션 목록 조회 시 도서 수 응답에 포함
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/response/CollectionListDetailRes.java
Labels: fix ⚒️

#66 [FIX] 컬렉션 내 도서 삭제 및 조회 시 CollectionBook 객체를 활용하도록 수정
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/domain/repository/CollectionBookRepository.java
Labels: fix ⚒️

#67 [FIX] 컬렉션 내 도서 삭제 및 조회 시 CollectionBook 객체를 활용하도록 수정
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/domain/repository/CollectionBookRepository.java
Labels: fix ⚒️

#69 [FEAT] 타이머 관련 API 구현
  build.gradle
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/book/presentation/BookController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/Timer.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/timer/dto/request/CreateTimerReq.java
  src/main/java/com/nookbook/domain/timer/dto/response/TimerRecordRes.java
  src/main/java/com/nookbook/domain/timer/dto/response/TimerRes.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: feature 🪽

#70 [DEPLOY]
  build.gradle
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/book/presentation/BookController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/Timer.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/timer/dto/request/CreateTimerReq.java
  src/main/java/com/nookbook/domain/timer/dto/response/TimerRecordRes.java
  src/main/java/com/nookbook/domain/timer/dto/response/TimerRes.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: cicd

#72 [FEAT] 이미지 업로드 및 삭제 API 구현
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/dto/response/ImageUrlRes.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/infrastructure/s3/S3Uploader.java
Labels: feature 🪽

#73 [DEPLOY]
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/dto/response/ImageUrlRes.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/infrastructure/s3/S3Uploader.java
Labels: cicd

#74 [DEPLOY]
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/dto/response/TimerRecordRes.java
Labels: cicd

#78 [FEAT] 챌린지 참여자 목록 조회 및 역할 정보 응답
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/application/ParticipantService.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ParticipantListRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ParticipantRes.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
Labels: feature 🪽

#80 [FEAT] S3 파일 업로드 시 FullPath를 저장하도록 수정
  src/main/java/com/nookbook/infrastructure/s3/S3Uploader.java
Labels: fix ⚒️

#82 [FIX] 챌린지 상세 조회 시 일일 독서 시작/종료 시간 응답 추가
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeDetailRes.java
Labels: fix ⚒️

#83 [FIX] 챌린지 관련 수정사항 반영
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/application/ParticipantService.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeDetailRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ParticipantListRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ParticipantRes.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/infrastructure/s3/S3Uploader.java
Labels: feature 🪽, fix ⚒️

#88 [FEAT] 기본 이미지 경로 설정
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/domain/user/dto/response/MyInfoRes.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: feature 🪽

#89 [DEPLOY]
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/domain/user/dto/response/MyInfoRes.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: cicd
