Repository Nook-Book/Server, pull requests merged in 2025-05, with the labels that each got.

#165 [DEPLOY]
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/presentation/FriendController.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: cicd

#167 [FIX] 로그아웃, 탈퇴 기능 오류 수정
  src/main/java/com/nookbook/domain/auth/application/AuthService.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: fix ⚒️

#168 [DEPLOY]
  src/main/java/com/nookbook/domain/auth/application/AuthService.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: cicd

#170 [FIX] 기존 사용자 존재 여부 반환 API security permit 추가
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: fix ⚒️

#171 [DEPLOY]
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: cicd

#173 [FIX] 미가입 사용자 판단 시 닉네임/아이디 설정 완료 여부 판단 로직 추가
  src/main/java/com/nookbook/domain/user/application/UserService.java
Labels: fix ⚒️

#174 [DEPLOY]
  src/main/java/com/nookbook/domain/user/application/UserService.java
Labels: cicd

#175 [FEAT] 컬렉션 간 도서 이동 기능 구현
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/request/TargetCollectionReq.java
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
Labels: feature 🪽, refactor ♻️

#176 [DEPLOY]
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/request/TargetCollectionReq.java
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
Labels: cicd

#178 [FIX] 컬렉션 내 도서 목록 조회 시, 작가 정보 응답 필드 추가
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/response/CollectionBooksListDetailRes.java
Labels: enhancement, fix ⚒️

#179 [DEPLOY]
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/dto/response/CollectionBooksListDetailRes.java
Labels: cicd

#183 [REFACTOR] 도서, 타이머, 노트, 마이페이지, 친구 URL 변경
  src/main/java/com/nookbook/domain/book/presentation/BookController.java
  src/main/java/com/nookbook/domain/keyword/presentation/KeywordController.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/dto/request/CreateNoteReq.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/dto/request/UpdateTimerReq.java
  src/main/java/com/nookbook/domain/timer/presentation/TimerController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/dto/request/FriendRequestDecisionReq.java
  src/main/java/com/nookbook/domain/user/dto/request/FriendRequestReq.java
  src/main/java/com/nookbook/domain/user/presentation/FriendController.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
  src/main/java/com/nookbook/domain/user/presentation/UserController.java
  src/main/java/com/nookbook/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nookbook/infrastructure/s3/S3Uploader.java
Labels: refactor ♻️

#181 [REFACTOR] Auth, 컬렉션, 챌린지, 알림 관련 url 수정
  src/main/java/com/nookbook/domain/alarm/presentation/AlarmController.java
  src/main/java/com/nookbook/domain/auth/presentation/AuthController.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
Labels: refactor ♻️

#184 [CICD] API 전반 url 수정
  src/main/java/com/nookbook/domain/alarm/presentation/AlarmController.java
  src/main/java/com/nookbook/domain/auth/presentation/AuthController.java
  src/main/java/com/nookbook/domain/book/presentation/BookController.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
  src/main/java/com/nookbook/domain/keyword/presentation/KeywordController.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/dto/request/CreateNoteReq.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/dto/request/UpdateTimerReq.java
  src/main/java/com/nookbook/domain/timer/presentation/TimerController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/dto/request/FriendRequestDecisionReq.java
  src/main/java/com/nookbook/domain/user/dto/request/FriendRequestReq.java
  src/main/java/com/nookbook/domain/user/presentation/FriendController.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
  src/main/java/com/nookbook/domain/user/presentation/UserController.java
  src/main/java/com/nookbook/global/config/security/SecurityConfig.java
  src/main/java/com/nookbook/global/exception/GlobalExceptionHandler.java
  src/main/java/com/nookbook/infrastructure/s3/S3Uploader.java
Labels: cicd
