Repository Nook-Book/Server, pull requests merged in 2025-02, with the labels that each got.

#92 [DEPLOY]
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/book/domain/Book.java
  src/main/java/com/nookbook/domain/book/dto/response/BookDetailRes.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/nookbook/domain/note/dto/response/OtherUserNoteListRes.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/Friend.java
  src/main/java/com/nookbook/domain/user/domain/FriendRequestStatus.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/dto/response/FriendsRequestRes.java
  src/main/java/com/nookbook/domain/user/dto/response/SearchUserRes.java
  src/main/java/com/nookbook/domain/user/dto/response/UserInfoRes.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
Labels: cicd

#93 [FEAT] 챌린지 내 친구 관련 기능 구현
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/application/InvitationService.java
  src/main/java/com/nookbook/domain/challenge/domain/Challenge.java
  src/main/java/com/nookbook/domain/challenge/domain/Invitation.java
  src/main/java/com/nookbook/domain/challenge/domain/InvitationStatus.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/InvitationRepository.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/ParticipantRepository.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeInvitationRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeListRes.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/Friend.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
Labels: feature 🪽

#94 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/application/InvitationService.java
  src/main/java/com/nookbook/domain/challenge/domain/Challenge.java
  src/main/java/com/nookbook/domain/challenge/domain/Invitation.java
  src/main/java/com/nookbook/domain/challenge/domain/InvitationStatus.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/InvitationRepository.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/ParticipantRepository.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeInvitationRes.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeListRes.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/Friend.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
Labels: feature 🪽

#96 [FEAT] 타이머 시작 API 구현
  src/main/java/com/nookbook/domain/book/presentation/BookController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/Timer.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/timer/dto/response/StartTimerIdRes.java
  src/main/java/com/nookbook/domain/timer/dto/response/TimerRes.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: feature 🪽

#97 [DEPLOY]
  src/main/java/com/nookbook/domain/book/presentation/BookController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/Timer.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/timer/dto/response/StartTimerIdRes.java
  src/main/java/com/nookbook/domain/timer/dto/response/TimerRes.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: cicd

#98 [FIX] 챌린지 생성 시 챌린지 ID 응답
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
Labels: fix ⚒️

#99 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
Labels: fix ⚒️

#100 [FIX] 챌린지 방장 변경 시 @Transactional 추가
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
Labels: fix ⚒️

#101 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
Labels: fix ⚒️

#102 [FIX] 챌린지 초대할 친구 목록 조회 시 페이징 처리 삭제
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
Labels: fix ⚒️

#103 [REFACTOR] 친구 API 페이징 삭제
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: feature 🪽

#104 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: cicd

#106 [FEAT] 일반 사용자의 챌린지 나가기 기능 구현
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/application/ParticipantService.java
  src/main/java/com/nookbook/domain/challenge/domain/Challenge.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/ParticipantRepository.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeInvitationRes.java
  src/main/java/com/nookbook/domain/challenge/exception/ChallengeOwnerCantLeaveException.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
Labels: feature 🪽

#107 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/application/ParticipantService.java
  src/main/java/com/nookbook/domain/challenge/domain/Challenge.java
  src/main/java/com/nookbook/domain/challenge/domain/repository/ParticipantRepository.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ChallengeInvitationRes.java
  src/main/java/com/nookbook/domain/challenge/exception/ChallengeOwnerCantLeaveException.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
Labels: feature 🪽, fix ⚒️

#110 [FEAT] 챌린지 참가자 현황 정보에 타이머 정보 추가 구현
  .github/ISSUE_TEMPLATE/feature_request.md
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ParticipantStatusListRes.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
Labels: feature 🪽

#111 [DEPLOY]
  .github/ISSUE_TEMPLATE/feature_request.md
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/dto/response/ParticipantStatusListRes.java
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
Labels: feature 🪽

#112 [FIX] 타이머 조회 오류 수정
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: fix ⚒️

#113 [DEPLOY]
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: cicd

#114 [FIX] 이미지 경로 표기 오류 및 크기 수정
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
Labels: fix ⚒️
