Repository Nook-Book/Server, pull requests merged in 2025-03, with the labels that each got.

#116 [FEAT] 기록 캘린더 조회 기능 구현
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user_book/application/UserBookService.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
  src/main/java/com/nookbook/domain/user_book/dto/response/DailyUserBookCalendarRes.java
  src/main/java/com/nookbook/domain/user_book/dto/response/MonthlyUserBookCalendarRes.java
  src/main/java/com/nookbook/domain/user_book/presentation/UserBookController.java
Labels: feature 🪽

#117 [DEPLOY]
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user_book/application/UserBookService.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
  src/main/java/com/nookbook/domain/user_book/dto/response/DailyUserBookCalendarRes.java
  src/main/java/com/nookbook/domain/user_book/dto/response/MonthlyUserBookCalendarRes.java
  src/main/java/com/nookbook/domain/user_book/presentation/UserBookController.java
Labels: cicd

#118 [HOTFIX] 로그인/로그아웃/탈퇴하기 관련 로직 @Transactional 추가
  src/main/java/com/nookbook/domain/auth/application/AuthService.java
Labels: fix ⚒️

#119 [FEAT] 챌린지 참가자별 독서 캘린더 조회 기능 구현
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/user_book/application/UserBookService.java
  src/main/java/com/nookbook/domain/user_book/presentation/UserBookController.java
Labels: feature 🪽

#120 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/nookbook/domain/user_book/application/UserBookService.java
  src/main/java/com/nookbook/domain/user_book/presentation/UserBookController.java
Labels: cicd

#122 [FEAT] 노트 비공개 여부 추가 구현
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/domain/Note.java
  src/main/java/com/nookbook/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/nookbook/domain/note/dto/request/CreateNoteReq.java
  src/main/java/com/nookbook/domain/note/dto/request/UpdateNoteReq.java
  src/main/java/com/nookbook/domain/note/dto/response/NoteDetailRes.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: feature 🪽

#123 [DEPLOY]
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/domain/Note.java
  src/main/java/com/nookbook/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/nookbook/domain/note/dto/request/CreateNoteReq.java
  src/main/java/com/nookbook/domain/note/dto/request/UpdateNoteReq.java
  src/main/java/com/nookbook/domain/note/dto/response/NoteDetailRes.java
  src/main/java/com/nookbook/domain/note/presentation/NoteController.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: cicd

#125 [FIX] 챌린지 상세 조회 시 타이머 조회 오류 수정
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
Labels: fix ⚒️

#126 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/timer/domain/repository/TimerRepository.java
  src/main/java/com/nookbook/domain/user_book/domain/repository/UserBookRepository.java
Labels: cicd

#127 [FIX] 챌린지 관련 수정사항 반영
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/domain/Challenge.java
Labels: fix ⚒️

#128 [DEPLOY]
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/challenge/domain/Challenge.java
Labels: cicd

#130 [FEAT] 회원가입된 유저 여부 조회 기능 구현
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/dto/response/UserExistsRes.java
  src/main/java/com/nookbook/domain/user/presentation/UserController.java
Labels: feature 🪽

#132 [FIX] registered user 판단 로직 수정
  src/main/java/com/nookbook/domain/user/application/UserService.java
Labels: fix ⚒️

#133 [DEPLOY]
  src/main/java/com/nookbook/domain/user/application/UserService.java
Labels: cicd

#135 [FEAT] 타이머 자동 업데이트 기능 구현
  build.gradle
  src/main/java/com/nookbook/NookBookApplication.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/infrastructure/batch/TimerBatchJobLauncher.java
  src/main/java/com/nookbook/infrastructure/batch/config/QuartzConfig.java
  src/main/java/com/nookbook/infrastructure/batch/config/TimerBatchConfig.java
  src/main/resources/application.yml
Labels: feature 🪽

#136 [DEPLOY]
  build.gradle
  src/main/java/com/nookbook/NookBookApplication.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/user_book/domain/UserBook.java
  src/main/java/com/nookbook/infrastructure/batch/TimerBatchJobLauncher.java
  src/main/java/com/nookbook/infrastructure/batch/config/QuartzConfig.java
  src/main/java/com/nookbook/infrastructure/batch/config/TimerBatchConfig.java
  src/main/resources/application.yml
Labels: cicd

#138 [DEPLOY]
  src/main/java/com/nookbook/domain/book/applicaiton/BookService.java
  src/main/java/com/nookbook/domain/challenge/application/ChallengeService.java
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/keyword/application/KeywordService.java
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/timer/application/TimerService.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user_book/application/UserBookService.java
Labels: cicd

#139 [FIX] 토큰 생성/검증 시 secretKey 디코딩 방식 통일 및 User Role 지정하도록 수정
  src/main/java/com/nookbook/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/global/config/security/util/JwtTokenUtil.java
Labels: fix ⚒️

#140 [DEPLOY]
  src/main/java/com/nookbook/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/global/config/security/util/JwtTokenUtil.java
Labels: fix ⚒️

#144 [DEPLOY]
  src/main/java/com/nookbook/domain/user/domain/User.java
Labels: cicd

#146 [FIX] 중복된 기본 컬렉션 생성 로직 삭제
  src/main/java/com/nookbook/domain/user/application/UserService.java
Labels: fix ⚒️

#147 [DEPLOY]
  src/main/java/com/nookbook/domain/user/application/UserService.java
Labels: cicd

#148 [FEAT] 컬렉션 삭제 기능 구현
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/domain/Collection.java
  src/main/java/com/nookbook/domain/collection/exception/CollectionAccessDeniedException.java
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
Labels: feature 🪽

#149 [DEPLOY]
  src/main/java/com/nookbook/domain/collection/application/CollectionService.java
  src/main/java/com/nookbook/domain/collection/domain/Collection.java
  src/main/java/com/nookbook/domain/collection/exception/CollectionAccessDeniedException.java
  src/main/java/com/nookbook/domain/collection/presentation/CollectionController.java
Labels: cicd

#153 [DOCS] 알림 타입 변경에 따른 명세 수정
  src/main/java/com/nookbook/domain/alarm/dto/response/AlarmRes.java
Labels: documentation

#154 [DEPLOY]
  src/main/java/com/nookbook/domain/alarm/dto/response/AlarmRes.java
Labels: cicd
