Repository Nook-Book/Server, pull requests merged in 2025-04, with the labels that each got.

#156 [DEPLOY]
  build.gradle
  src/main/java/com/nookbook/domain/alarm/application/AlarmPushService.java
  src/main/java/com/nookbook/domain/alarm/application/AlarmService.java
  src/main/java/com/nookbook/domain/alarm/message/AlarmMessageFactory.java
  src/main/java/com/nookbook/domain/auth/application/AuthService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/User.java
  src/main/java/com/nookbook/domain/user/dto/request/ExpoPushTokenReq.java
  src/main/java/com/nookbook/domain/user/presentation/UserController.java
  src/main/java/com/nookbook/global/config/PushClientConfig.java
  src/main/java/com/nookbook/global/notification/ExpoNotificationSender.java
Labels: cicd

#157 [FIX] 독서 기록 종료 시간 조회 오류
  src/main/java/com/nookbook/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/nookbook/domain/user_book/application/UserBookService.java
Labels: fix ⚒️

#158 [DEPLOY]
  src/main/java/com/nookbook/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/nookbook/domain/user_book/application/UserBookService.java
Labels: cicd

#160 [REFACTOR] 기록 전체보기 형식 수정
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: feature 🪽

#161 [DEPLOY]
  src/main/java/com/nookbook/domain/note/application/NoteService.java
  src/main/java/com/nookbook/domain/note/domain/repository/NoteRepository.java
  src/main/java/com/nookbook/domain/user/application/FriendService.java
  src/main/java/com/nookbook/domain/user/application/UserService.java
  src/main/java/com/nookbook/domain/user/domain/repository/FriendRepository.java
  src/main/java/com/nookbook/domain/user/domain/repository/UserRepository.java
  src/main/java/com/nookbook/domain/user/presentation/MyPageController.java
Labels: cicd
